connections: # 要自动化部署的连接
  - ssh.web-01

remote_folder: "/app/demo/"  # 远端的部署文件夹

frontend: # 前端部署配置
  pre_action: # 部署前置命令
    - "pwd"
  post_action: # 部署后置命令
    - "pwd"

backend: # 后端部署配置
  goos: linux # 部署目标操作系统
  goarch: amd64 # 部署目标cpu架构
  pre_action: # 部署前置命令
    - 'find /app/demo -maxdepth 1 -type f -exec rm -f {} \;'
  post_action: # 部署后置命令
    - "chmod 777 /app/demo/hade"
    - "/app/demo/hade app restart"