timeout: 1s
network: tcp
web-01:
  host: 47.97.21.20 # ip地址
  port: 22 # 端口
  username: root # 用户名
  password: "Kerowsqw34." # 密码
web-02:
  network: tcp
  host: localhost # ip地址
  port: 3306 # 端口
  username: jianfengye # 用户名
  rsa_key: "/Users/user/.ssh/id_rsa"
  known_hosts: "/Users/user/.ssh/known_hosts"